# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: "I'm OWenT"
subtitle: "Chanllege Everything"
description: "OWenT' Blog"
author: OWenT
language: [zh-CN,en]
timezone: 'Asia/Shanghai'

i18n:
  type: [page, post]
  generator: [index, archive, category, tag]

# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: https://owent.net
root: /
permalink: posts/:year/:id
permalink_defaults: :year/:title

# Directory
source_dir: source
public_dir: source/_posts
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render: '**/*/README.md'

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link: true # Open external links in new tab
filename_case: 0
render_drafts: false
post_asset_folder: true
relative_link: false
future: true
highlight:
  enable: false         # set false to use highlight.js in client mode
  style: "default"      # style name
  langs: ['capnproto', 'cmake', 'd', 'dos', 'erlang', 'go', 'less', 'lua', 'php', 'powershell', 'protobuf', 'profile', 'typescript', 'vim']
  selector: 'pre>code'
  url:                  # 
    js: "//cdnjs.cloudflare.com/ajax/libs/highlight.js/<%- version %>/highlight.min.js"
    style: "//cdnjs.cloudflare.com/ajax/libs/highlight.js/<%- version %>/styles/<%- style %>.min.css"
    lang: "//cdnjs.cloudflare.com/ajax/libs/highlight.js/<%- version %>/languages/<%- lang %>.min.js"
  options:              # options of highlight.js see http://highlightjs.readthedocs.io/en/latest/api.html#configure-options
    tabReplace: '    '
    useBR: false
    #classPrefix: 'hljs-'
    languages: {}   # language alias

# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# theme configure
menu:
  Home: /
  Archives: /archives
  About: /about
rss: /atom.xml
favicon: /favicon.ico
widgets:
- recent_posts
- tagcloud
- archive

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
theme: distinctionpp

# Deployment
## Docs: https://hexo.io/docs/deployment.html
deploy:
  type:

math:
  engine: 'mathjax' # mathjax or 'katex'
  # katex:
  #   css: "https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.7.1/katex.min.css"
  #   js: "https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.7.1/katex.min.js" # not used
  #   config: {
  #     throwOnError: false,
  #     errorColor: "#cc0000"
  #   }
  mathjax:
    src: //cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.1/MathJax.js?config=TeX-AMS-MML_HTMLorMML
  #   config:
  #     # MathJax config

# Markdown-it config
## Docs: https://github.com/celsomiranda/hexo-renderer-markdown-it/wiki
markdown:
  render:
    html: true
    xhtmlOut: false
    breaks: true
    linkify: true
    typographer: true
    quotes: '“”‘’'
  plugins:
    - markdown-it-abbr
    - markdown-it-footnote
    - markdown-it-ins
    - markdown-it-sub
    - markdown-it-sup
  anchors:
    level: 4
    collisionSuffix: 'v'
    permalink: true
    permalinkClass: header-anchor
    permalinkSymbol: ¶

toc:
  maxdepth: 4
  class: toc
  slugify: transliteration

excerpt_depth: 5
excerpt_characters: 300

sitemap:
    path: sitemap.xml
    tag: true
    category: false

google_analytics: 'UA-19298704-1'
disqus_shortname: owent
disqus_on_page: false
# gitment:
#   enable_on_page: false
#   js: https://imsun.github.io/gitment/dist/gitment.browser.js
#   css: https://imsun.github.io/gitment/style/default.css
#   owner: owt5008137
#   repo: 'owent-blog-comment'
#   oauth:
#     client_id: 
#     client_secret: 